# Fcitx5 Signature Styles — generated
# Cyberpunk-AcidRain · 赛博朋克·酸雨
# Compact vertical layout with paging buttons hidden.
[Basic]
Theme=System

[LightMode]
OverrideDefault=True
HighlightColor=#57730d
HighlightHoverColor=#0f8075
HighlightTextColor=#ffffff
HighlightTextPressColor=#ffffff
HighlightLabelColor=#ffffff
HighlightCommentColor=#ffffff
HighlightMarkColor=#ffffff
PanelColor=#effcff
TextColor=#18313a
LabelColor=#526870
CommentColor=#526870
PagingButtonColor=#526870
DisabledPagingButtonColor=#526870
AuxColor=#18313a
PreeditColorPreCaret=#18313a
PreeditColorCaret=#b7f21b
PreeditColorPostCaret=#526870
BorderColor=#c0cfd4
DividerColor=#effcff

[DarkMode]
OverrideDefault=True
HighlightColor=#b7f21b
HighlightHoverColor=#17c3b2
HighlightTextColor=#17171b
HighlightTextPressColor=#17171b
HighlightLabelColor=#17171b
HighlightCommentColor=#17171b
HighlightMarkColor=#17171b
PanelColor=#09121c
TextColor=#e7fbff
LabelColor=#9fb5bd
CommentColor=#9fb5bd
PagingButtonColor=#9fb5bd
DisabledPagingButtonColor=#9fb5bd
AuxColor=#e7fbff
PreeditColorPreCaret=#e7fbff
PreeditColorCaret=#b7f21b
PreeditColorPostCaret=#9fb5bd
BorderColor=#404c55
DividerColor=#09121c
SameWithLightMode=False

[Typography]
Layout=Vertical
WritingMode="Vertical right-left"
TypographyAwarenessForIM=False
VerticalCommentsAlignRight=True
PagingButtonsStyle=None

[Background]
ImageUrl=
KeepPanelColorWhenHasImage=False
Blur=System
Shadow=True

[Font]
TextFontSize=15
TextFontWeight=400
LabelFontSize=10
LabelFontWeight=400
CommentFontSize=11
CommentFontWeight=400
PreeditFontSize=13
PreeditFontWeight=400

[Font/TextFontFamily]
0="PingFang SC"
1="Helvetica Neue"
2=sans-serif

[Font/LabelFontFamily]
0="SF Mono"
1=Menlo
2=monospace

[Font/CommentFontFamily]
0="PingFang SC"
1="Helvetica Neue"
2=sans-serif

[Font/PreeditFontFamily]
0="SF Mono"
1="PingFang SC"
2=monospace

[Caret]
Style=Blink
Text=‸

[Highlight]
MarkStyle=Bar
MarkText=●
HoverBehavior=None

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=4
Margin=3
HighlightRadius=5
TopPadding=3
RightPadding=8
BottomPadding=3
LeftPadding=8
LabelTextGap=5
VerticalMinWidth=190
ScrollCellWidth=65
HorizontalDividerWidth=0

[Advanced]
UserCss=fcitx:///file/css/signature-cyberpunk-acidrain.css

