# Fcitx5 Signature Styles — generated
# Vaporwave-OceanDream · 蒸汽波·海洋梦境
# Compact vertical layout with paging buttons hidden.
[Basic]
Theme=System

[LightMode]
OverrideDefault=True
HighlightColor=#5d60e8
HighlightHoverColor=#137c7a
HighlightTextColor=#ffffff
HighlightTextPressColor=#ffffff
HighlightLabelColor=#ffffff
HighlightCommentColor=#ffffff
HighlightMarkColor=#ffffff
PanelColor=#fff0fa
TextColor=#38233f
LabelColor=#6c5373
CommentColor=#6c5373
PagingButtonColor=#6c5373
DisabledPagingButtonColor=#6c5373
AuxColor=#38233f
PreeditColorPreCaret=#38233f
PreeditColorCaret=#5d60e8
PreeditColorPostCaret=#6c5373
BorderColor=#d3c3d1
DividerColor=#fff0fa

[DarkMode]
OverrideDefault=True
HighlightColor=#7c7eec
HighlightHoverColor=#20d2d0
HighlightTextColor=#17171b
HighlightTextPressColor=#17171b
HighlightLabelColor=#17171b
HighlightCommentColor=#17171b
HighlightMarkColor=#17171b
PanelColor=#181128
TextColor=#f9eaff
LabelColor=#c0aace
CommentColor=#c0aace
PagingButtonColor=#c0aace
DisabledPagingButtonColor=#c0aace
AuxColor=#f9eaff
PreeditColorPreCaret=#f9eaff
PreeditColorCaret=#5d60e8
PreeditColorPostCaret=#c0aace
BorderColor=#50475e
DividerColor=#181128
SameWithLightMode=False

[Typography]
Layout=Vertical
WritingMode="Vertical right-left"
TypographyAwarenessForIM=False
VerticalCommentsAlignRight=True
PagingButtonsStyle=None

[Background]
ImageUrl=
KeepPanelColorWhenHasImage=False
Blur=System
Shadow=True

[Font]
TextFontSize=15
TextFontWeight=400
LabelFontSize=10
LabelFontWeight=400
CommentFontSize=11
CommentFontWeight=400
PreeditFontSize=13
PreeditFontWeight=400

[Font/TextFontFamily]
0="PingFang SC"
1="Helvetica Neue"
2=sans-serif

[Font/LabelFontFamily]
0="SF Mono"
1=Menlo
2=monospace

[Font/CommentFontFamily]
0="PingFang SC"
1="Helvetica Neue"
2=sans-serif

[Font/PreeditFontFamily]
0="SF Mono"
1="PingFang SC"
2=monospace

[Caret]
Style=Blink
Text=‸

[Highlight]
MarkStyle=Bar
MarkText=●
HoverBehavior=None

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=10
Margin=3
HighlightRadius=5
TopPadding=3
RightPadding=8
BottomPadding=3
LeftPadding=8
LabelTextGap=5
VerticalMinWidth=190
ScrollCellWidth=65
HorizontalDividerWidth=0

[Advanced]
UserCss=fcitx:///file/css/signature-vaporwave-oceandream.css

