# Fcitx5 Signature Styles — generated
# Y2K-AquaPlastic · Y2K·水色塑料
# Compact vertical layout with paging buttons hidden.
[Basic]
Theme=System

[LightMode]
OverrideDefault=True
HighlightColor=#1d7671
HighlightHoverColor=#447887
HighlightTextColor=#ffffff
HighlightTextPressColor=#ffffff
HighlightLabelColor=#ffffff
HighlightCommentColor=#ffffff
HighlightMarkColor=#ffffff
PanelColor=#f8fbff
TextColor=#30303c
LabelColor=#666676
CommentColor=#666676
PagingButtonColor=#666676
DisabledPagingButtonColor=#666676
AuxColor=#30303c
PreeditColorPreCaret=#30303c
PreeditColorCaret=#31c8c0
PreeditColorPostCaret=#666676
BorderColor=#ccced4
DividerColor=#f8fbff

[DarkMode]
OverrideDefault=True
HighlightColor=#31c8c0
HighlightHoverColor=#80e1ff
HighlightTextColor=#17171b
HighlightTextPressColor=#17171b
HighlightLabelColor=#17171b
HighlightCommentColor=#17171b
HighlightMarkColor=#17171b
PanelColor=#161724
TextColor=#f4f0ff
LabelColor=#b9b4ca
CommentColor=#b9b4ca
PagingButtonColor=#b9b4ca
DisabledPagingButtonColor=#b9b4ca
AuxColor=#f4f0ff
PreeditColorPreCaret=#f4f0ff
PreeditColorCaret=#31c8c0
PreeditColorPostCaret=#b9b4ca
BorderColor=#4e4d5b
DividerColor=#161724
SameWithLightMode=False

[Typography]
Layout=Vertical
WritingMode="Vertical right-left"
TypographyAwarenessForIM=False
VerticalCommentsAlignRight=True
PagingButtonsStyle=None

[Background]
ImageUrl=
KeepPanelColorWhenHasImage=False
Blur=System
Shadow=True

[Font]
TextFontSize=15
TextFontWeight=400
LabelFontSize=10
LabelFontWeight=400
CommentFontSize=11
CommentFontWeight=400
PreeditFontSize=13
PreeditFontWeight=400

[Font/TextFontFamily]
0="Avenir Next"
1="PingFang SC"
2=sans-serif

[Font/LabelFontFamily]
0="SF Mono"
1=Menlo
2=monospace

[Font/CommentFontFamily]
0="Avenir Next"
1="PingFang SC"
2=sans-serif

[Font/PreeditFontFamily]
0="SF Mono"
1="PingFang SC"
2=monospace

[Caret]
Style=Blink
Text=‸

[Highlight]
MarkStyle=Bar
MarkText=●
HoverBehavior=None

[Size]
OverrideDefault=True
BorderWidth=1
BorderRadius=12
Margin=3
HighlightRadius=5
TopPadding=3
RightPadding=8
BottomPadding=3
LeftPadding=8
LabelTextGap=5
VerticalMinWidth=190
ScrollCellWidth=65
HorizontalDividerWidth=0

[Advanced]
UserCss=fcitx:///file/css/signature-y2k-aquaplastic.css

